---
kind: pipeline
type: kubernetes
name: build
trigger:
  event:
    - push
    - tag

steps:
  - name: test project
    image: quay.io/ukhomeofficedigital/hocs-base-image-build
    commands:
      - ./gradlew clean build --no-daemon

---
kind: pipeline
type: kubernetes
name: publish
trigger:
  event:
    - tag
depends_on:
  - build

steps:
  - name: publish
    pull: if-not-exists
    image: maven:3.8.3-openjdk-17
    environment:
      ARTIFACTORY_TOKEN:
        from_secret: ARTIFACTORY_TOKEN
      ARTIFACTORY_USER:
        from_secret: ARTIFACTORY_USER
      PACKAGE_TOKEN:
        from_secret: PACKAGE_TOKEN
    commands:
      - ./gradlew publish -PartifactVersion=${DRONE_TAG}
