---

kind: pipeline
type: kubernetes
name: build

steps:
  - name: test project
    image: quay.io/ukhomeofficedigital/hocs-base-image-build:1.0.2
    commands:
      - ./gradlew clean build --no-daemon

trigger:
  event:
    - push
    - tag

---
kind: pipeline
type: kubernetes
name: publish

steps:

  - name: publish
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/java11-mvn:v3.5.4
    environment:
      ARTIFACTORY_TOKEN:
        from_secret: ARTIFACTORY_TOKEN
      ARTIFACTORY_USER:
        from_secret: ARTIFACTORY_USER
    commands:
      - ./gradlew publish -PartifactVersion=${DRONE_TAG}

depends_on:
- build

trigger:
  event:
    - tag
...
